# Generated by Django 5.2.7 on 2026-06-30 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('department_name', models.CharField(blank=True, default='', max_length=255)),
                ('client', models.CharField(max_length=50)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('expense_type', models.CharField(choices=[('Self/Personal Expense', 'Self/Personal Expense'), ('Travel/Public Transport Expense', 'Travel/Public Transport Expense'), ('Food/Meal Expense', 'Food/Meal Expense'), ('Accommodation Expense', 'Accommodation Expense'), ('Fuel Expense/Parking and Toll Expense', 'Fuel Expense/Parking and Toll Expense'), ('Other Expense', 'Other Expense')], max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('receipt', models.FileField(blank=True, null=True, upload_to='claims/receipts/%Y/%m/')),
                ('status', models.CharField(choices=[('Claimed', 'Claimed'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Claimed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
