# Generated by Django 5.2.7 on 2026-06-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='created_by_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='claim',
            name='expense_type',
            field=models.CharField(max_length=64),
        ),
    ]
