# Generated by Django 5.2.7 on 2026-06-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0002_alter_feeder_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='adm_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Verified', 'Verified')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='feeder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Key Uploaded', 'Key Uploaded'), ('Under Progress', 'Under Progress')], default='Pending', max_length=20),
        ),
    ]
