# Generated by Django 6.0.6 on 2026-06-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0003_alter_feeder_adm_status_alter_feeder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='unique_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
