# Generated by Django 6.0.6 on 2026-06-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0004_add_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Installed', 'Installed')], default='Pending', max_length=20),
        ),
    ]
