# Generated by Django 6.0.6 on 2026-06-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0005_update_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeder',
            name='modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
