# Generated by Django 6.0.6 on 2026-06-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientmaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmaster',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
