# Generated by Django 6.0.6 on 2026-06-24 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_corporate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='businessnature',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='corporate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='software',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ClientMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('type', models.CharField(blank=True, default='', max_length=30)),
                ('suc_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('suc_end_date', models.DateField(blank=True, null=True)),
                ('payment_class', models.CharField(blank=True, default='', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('place', models.CharField(blank=True, default='', max_length=200)),
                ('pin_code', models.CharField(blank=True, default='', max_length=10)),
                ('person_name', models.CharField(blank=True, default='', max_length=200)),
                ('reputed_person_name', models.CharField(blank=True, default='', max_length=200)),
                ('phone1', models.CharField(blank=True, default='', max_length=20)),
                ('phone2', models.CharField(blank=True, default='', max_length=20)),
                ('phone3', models.CharField(blank=True, default='', max_length=20)),
                ('reputed_person1', models.CharField(blank=True, default='', max_length=20)),
                ('reputed_person2', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('account_link', models.CharField(blank=True, default='', max_length=500)),
                ('licence_type', models.CharField(blank=True, default='', max_length=30)),
                ('no_of_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('software_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='master.branch')),
                ('business_nature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='master.businessnature')),
                ('corporate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='master.corporate')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='master.country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='master.district')),
                ('service_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='master.sp')),
                ('software', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='master.software')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='master.state')),
            ],
            options={
                'db_table': 'master_clientmaster',
                'ordering': ['name'],
            },
        ),
    ]
