# Generated by Django 6.0.6 on 2026-06-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_alter_branch_id_alter_businessnature_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientMaster',
        ),
    ]
