# Generated by Django 6.0.6 on 2026-06-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_delete_clientmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master_module',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
