# Generated by Django 5.2.7 on 2026-06-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='installation_keys/'),
        ),
    ]
